export * as magicSeven from "./commands/magicSeven";
export * as hi from "./commands/hi";
export * as rate from "./commands/rate";
export * as urbanDictionary from "./commands/urbanDictionary";
export * as bee from "./commands/bee";
export * as pokemon from "./commands/pokemon";
export * as about from "./commands/about";
export * as butterfree from "./commands/byebutterfree";
export * as where from "./commands/where";